name: Feature request
description: Suggest an idea for this project
title: "[Idea]: "
labels: ["enhancement"]
assignees:
  - yikeda6616
body:
  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve with this program as it
        currently stands?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        Clear and concise description of what you want to happen. Please use examples
        of real world use cases that this would help with, and how it solves the
        problem described above.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: >-
        Have you tried to workaround the problem using this program or other tools? Or a
        different approach to solving this issue? Please elaborate here.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context, links, etc. relevant to the feature request.
    validations:
      required: false
